name: PSGallery Publish
env:
 PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
on:
  push:
    branches:
      - main

jobs:
  publish-to-psgallery:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Deploy Package
        shell: pwsh
        run: |
          Publish-Module -Path "./PwshPaint/" -NugetApiKey $env:PSGALLERY_API_KEY
